"""rename address

Revision ID: cabd6528ade0
Revises: 02a2d896648f
Create Date: 2024-06-28 01:16:04.112720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabd6528ade0'
down_revision = '02a2d896648f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'location',  new_column_name='address')
    # ### end Alembic commands ###
